
#define F_CPU 8000000UL
#include "../LIB/STD_TYPES.h"
#include "../LIB/BIT_MATH.h"
#include "../MCAL/Timers/Timers.h"
#include "../HAL/LED/LED.h"
#include "../HAL/LED/LED_Config.h"





 /**
 *@ delay function implemented in assembly code
 */
void _delay_ms( int volatile milliseconds)
{
	/*
	assembly code auto generated by utility
	from bret mulvey 
	delay 8 000 cycles
	1ms at 8.0 MZ
	*/
	while(milliseconds--)
	{
	asm volatile(
	"     ldi   r18, 11   \n"
	"     ldi   r19, 99   \n"
	"1:   dec   r19   \n "
	"     brne  1b    \n"
	"     dec   r18   \n"
	"     brne  1b    \n"  
	);
	
	}
	

}
u8 toggle = 0;
void func1(void)
{
		/**
		*@ toggle led and break loop
		*/
			
			
				if(toggle == 0)
				{
					LED_enuSetLedState(LED1,LED_enumActiveHigh_ON);
					
					toggle ^= 1;
				}
				else
				{
					LED_enuSetLedState(LED1,LED_enumActiveHigh_OFF);
					
					toggle ^= 1;
				}
			
			
}



int main(void)
{
	TIMER2_enuSetOVFINT(func1);

	LED_enumdInit();

	Timer2_enumSetTimer_OV(1000000);
	
    
	while(1)
    {
         
    }
}