
#define F_CPU 8000000UL
#include "../LIB/STD_TYPES.h"
#include "../LIB/BIT_MATH.h"
#include "../MCAL/DIO_04/DIO.h"
#include "../MCAL/DIO_04/DIO_Private.h"
#include "../MCAL/ExtInterrupt/ExtInterrupt_Private.h"
#include "../MCAL/ExtInterrupt/ExtInterrupt.h"
#include "../MCAL/ExtInterrupt/ExtInterrupt_CFG.h"
#include "../HAL/LED/LED.h"
#include "../HAL/LED/LED_Config.h"
#include "../HAL/SWITCH/SWITCH.h"
#include "../HAL/SWITCH/SWITCH_Config.h"
#include "../HAL/7_SEGMENTS/SevenSegments.h"
#include "../HAL/7_SEGMENTS/SevenSegments_Config.h"

 /**
 *@ delay function implemented in assembly code
 */
void _delay_ms( int volatile milliseconds)
{
	/*
	assembly code auto generated by utility
	from bret mulvey 
	delay 8 000 cycles
	1ms at 8.0 MZ
	*/
	while(milliseconds--)
	{
	asm volatile(
	"     ldi   r18, 11   \n"
	"     ldi   r19, 99   \n"
	"1:   dec   r19   \n "
	"     brne  1b    \n"
	"     dec   r18   \n"
	"     brne  1b    \n"  
	);
	
	}
	

}


/**
*@ function 1 to test ext int 0
*/
void func1(void)
{
		/**
		*@ toggle led and break loop
		*/
			LED_enuSetLedState(LED1,LED_enumActiveHigh_ON);
			_delay_ms(250);
			
			LED_enuSetLedState(LED2,LED_enumActiveHigh_OFF);
			_delay_ms(250);
			
}
/***********************************/
void func2(void)
{		
		/**
		*@ toggle led and break loop
		*/
			LED_enuSetLedState(LED2,LED_enumActiveHigh_ON);
			_delay_ms(250);
				
			LED_enuSetLedState(LED1,LED_enumActiveHigh_OFF);
			_delay_ms(250);
}
/****************************************************/

int main(void)
{
	/**
	*@ set call back function for external interrupt 0
	*/
	ExtINT_voidSetExtINT0(func1);
	/**
	*@ set call back function for external interrupt 1
	*/
	ExtINT_voidSetExtINT1(func2);
	
	/**
	*@ external interrupt init function
	*/
	ExtInterrupt_voidInit();
	/**
	*@ LED init function
	*/
	LED_enumdInit();
	/**
	*@ switch init function
	*/
	SWITCH_enumdInit();
	/**
	*@ seven segments init function
	*/
	SevenSegments_enumInit();
	/**
	*@ set call back function for external interrupt 0
	*/
	ExtINT_voidSetExtINT0(func1);
	/**
	*@ set call back function for external interrupt 1
	*/
	ExtINT_voidSetExtINT1(func2);
	
	
	
    while(1)
    {
         
    }

return 0;
}




