




void delay_ms( int volatile milliseconds)
{
	/*
	assembly code auto generated by utility
	from bret mulvey 
	delay 8 000 cycles
	1ms at 8.0 MZ
	*/
	while(milliseconds--)
	{
	asm volatile(
	"     ldi   r18, 11   \n"
	"     ldi   r19, 99   \n"
	"1:   dec   r19   \n "
	"     brne  1b    \n"
	"     dec   r18   \n"
	"     brne  1b    \n"  
	);
	
	}
	

}